[project]
name = "claude-configs"
version = "0.1.0"
description = "Configuration files for Claude AI agents providing standardized commands and workflows for software development"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
